# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "GST Invoice & Shipping Manager"
client_id = "7a6fca531dee436fcecd8536fc3cb72e"
application_url = "https://invoiceo.indigenservices.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_orders,read_orders,write_customers,read_customers,write_products,read_products,write_shipping,read_shipping"

[auth]
redirect_urls = [
  "https://invoiceo.indigenservices.com/auth/callback",
  "https://invoiceo.indigenservices.com/auth/shopify/callback",
  "https://localhost:3000/auth/callback",
  "https://localhost:3000/auth/shopify/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "https://your-dev-store.myshopify.com"
include_config_on_deploy = true